package extractor

// Tests for Form XObject text extraction (Do operator support).
//
// Root cause: PDFs generated by TCPDF (and similar generators) place all page
// content inside Form XObjects invoked via the Do operator. The TextExtractor
// previously ignored Do, producing empty results for such pages.
//
// This file tests:
//  1. Basic Form XObject text extraction (SimpleFont/WinAnsi)
//  2. Type0 CID font text extraction inside an XObject (the TCPDF pattern)
//  3. Nested Form XObjects (XObject inside XObject)
//  4. Depth-capped recursion (guard against infinite loops)
//  5. Non-Form XObjects (Image XObjects) — must be skipped
//  6. Missing XObject reference — must not panic
//  7. Integration: real Correo Argentino PDF (5 pages, TCPDF-generated)

import (
	"bytes"
	"compress/zlib"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/coregx/gxpdf/internal/parser"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// ─── PDF builder helpers ──────────────────────────────────────────────────────

// xobjPDFBuilder accumulates objects and xref entries for minimal test PDFs.
type xobjPDFBuilder struct {
	buf     bytes.Buffer
	offsets []int64 // 1-indexed (index 0 is free entry)
	nextObj int
}

func newXObjPDFBuilder(maxObjs int) *xobjPDFBuilder {
	b := &xobjPDFBuilder{offsets: make([]int64, maxObjs+1)}
	b.buf.WriteString("%PDF-1.7\n")
	b.nextObj = 1
	return b
}

func (b *xobjPDFBuilder) addRaw(body string) int {
	n := b.nextObj
	b.nextObj++
	b.offsets[n] = int64(b.buf.Len())
	fmt.Fprintf(&b.buf, "%d 0 obj\n%s\nendobj\n", n, body)
	return n
}

func (b *xobjPDFBuilder) addStream(dict string, content []byte) int {
	n := b.nextObj
	b.nextObj++
	b.offsets[n] = int64(b.buf.Len())
	fmt.Fprintf(&b.buf, "%d 0 obj\n<< %s /Length %d >>\nstream\n", n, dict, len(content))
	b.buf.Write(content)
	b.buf.WriteString("\nendstream\nendobj\n")
	return n
}

func (b *xobjPDFBuilder) addCompressedStream(dict string, content []byte, t *testing.T) int {
	t.Helper()
	var cbuf bytes.Buffer
	w := zlib.NewWriter(&cbuf)
	_, err := w.Write(content)
	require.NoError(t, err)
	require.NoError(t, w.Close())
	return b.addStream(dict+"/Filter /FlateDecode", cbuf.Bytes())
}

func (b *xobjPDFBuilder) finalize(rootObj int) []byte {
	xrefOffset := int64(b.buf.Len())
	total := b.nextObj
	fmt.Fprintf(&b.buf, "xref\n0 %d\n", total)
	b.buf.WriteString("0000000000 65535 f \n")
	for i := 1; i < total; i++ {
		if b.offsets[i] == 0 {
			b.buf.WriteString("0000000000 65535 f \n")
		} else {
			fmt.Fprintf(&b.buf, "%010d 00000 n \n", b.offsets[i])
		}
	}
	fmt.Fprintf(&b.buf, "trailer\n<< /Size %d /Root %d 0 R >>\nstartxref\n%d\n%%%%EOF\n",
		total, rootObj, xrefOffset)
	return b.buf.Bytes()
}

// buildSimpleFontXObjectPDF constructs a PDF where the page content stream only
// invokes a Form XObject via "Do". The XObject contains text using a simple
// WinAnsiEncoding Type1 font.
//
// A Form XObject IS a stream — its content operators are the stream body.
// There is no separate /Contents indirection.
//
// Expected extracted text on page 0: "Hello World"
//
//nolint:funlen // PDF construction is inherently verbose
func buildSimpleFontXObjectPDF(t *testing.T) []byte {
	t.Helper()

	b := newXObjPDFBuilder(15)

	// Font dictionary for F1 (Helvetica / WinAnsi) — used inside XObject
	fontN := b.addRaw("<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>")

	// Form XObject: a stream whose body IS the content operators.
	// Dict header declares /Subtype /Form, /BBox, and /Resources.
	xobjContent := []byte("BT /F1 12 Tf 10 700 Td (Hello World) Tj ET")
	xobjN := b.addStream(
		fmt.Sprintf("/Type /XObject /Subtype /Form /BBox [0 0 612 792] /Resources << /Font << /F1 %d 0 R >> >>", fontN),
		xobjContent,
	)

	// Page content stream: invoke the Form XObject
	pageContentN := b.addStream("", []byte("/TPL1 Do"))

	// Page
	pageN := b.addRaw(fmt.Sprintf(
		"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /XObject << /TPL1 %d 0 R >> >> /Contents %d 0 R >>",
		xobjN, pageContentN,
	))

	// Pages
	pagesN := b.addRaw(fmt.Sprintf("<< /Type /Pages /Kids [%d 0 R] /Count 1 >>", pageN))

	// Catalog
	catalogN := b.addRaw(fmt.Sprintf("<< /Type /Catalog /Pages %d 0 R >>", pagesN))

	return b.finalize(catalogN)
}

// buildType0XObjectPDF constructs a PDF that mimics the TCPDF Correo Argentino
// pattern: all text is inside a Form XObject, and the font is Type0 with
// Identity-H encoding + a ToUnicode CMap using bfrange scalar form.
//
// Font: Type0/Identity-H with CMap: 0x0043→'C', 0x0049→'I', 0x0044→'D'
// Content: TJ with 2-byte glyph codes for "CID"
//
//nolint:funlen // PDF construction is inherently verbose
func buildType0XObjectPDF(t *testing.T) []byte {
	t.Helper()

	// ToUnicode CMap with 256-wide bfrange entries (TCPDF style: full Unicode
	// passthrough via 256-entry scalar ranges).
	// This maps every 2-byte code 0xXXYY to the Unicode code point 0xXXYY.
	// For our test we only need 0x0043→C, 0x0049→I, 0x0044→D.
	toUnicodeCMap := `/CIDInit /ProcSet findresource begin
12 dict begin
begincmap
/CIDSystemInfo << /Registry (Adobe) /Ordering (UCS) /Supplement 0 >> def
/CMapName /Adobe-Identity-UCS def
/CMapType 2 def
1 begincodespacerange
<0000> <FFFF>
endcodespacerange
2 beginbfrange
<0040> <0049> <0040>
<0040> <0044> <0040>
endbfrange
endcmap
end end
`

	b := newXObjPDFBuilder(20)

	// ToUnicode stream (uncompressed)
	toUnicodeN := b.addStream("", []byte(toUnicodeCMap))

	// Type0 font with Identity-H encoding + ToUnicode
	fontN := b.addRaw(fmt.Sprintf(
		"<< /Type /Font /Subtype /Type0 /BaseFont /AAAAAB+TestFont /Encoding /Identity-H /ToUnicode %d 0 R >>",
		toUnicodeN,
	))

	// Form XObject: the stream body IS the content operators.
	// 2-byte glyph codes: 0x0043='C' 0x0049='I' 0x0044='D'
	xobjContent := []byte("BT /F1 12 Tf 10 700 Td [(\x00\x43\x00\x49\x00\x44)] TJ ET")
	xobjN := b.addStream(
		fmt.Sprintf("/Type /XObject /Subtype /Form /BBox [0 0 612 792] /Resources << /Font << /F1 %d 0 R >> >>", fontN),
		xobjContent,
	)

	// Page content: just /TPL1 Do
	pageContentN := b.addStream("", []byte("/TPL1 Do"))

	// Page — no fonts in the page's own Resources (they are in the XObject)
	pageN := b.addRaw(fmt.Sprintf(
		"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /XObject << /TPL1 %d 0 R >> >> /Contents %d 0 R >>",
		xobjN, pageContentN,
	))

	// Pages
	pagesN := b.addRaw(fmt.Sprintf("<< /Type /Pages /Kids [%d 0 R] /Count 1 >>", pageN))

	// Catalog
	catalogN := b.addRaw(fmt.Sprintf("<< /Type /Catalog /Pages %d 0 R >>", pagesN))

	return b.finalize(catalogN)
}

// buildNestedXObjectPDF builds a PDF with two levels of XObject nesting.
//
// Page → XObject L1 → XObject L2 → text "Nested"
//
//nolint:funlen // PDF construction is inherently verbose
func buildNestedXObjectPDF(t *testing.T) []byte {
	t.Helper()

	b := newXObjPDFBuilder(20)

	// Font shared across both levels
	fontN := b.addRaw("<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>")

	// L2 Form XObject: actual text in its stream body
	l2N := b.addStream(
		fmt.Sprintf("/Type /XObject /Subtype /Form /BBox [0 0 612 792] /Resources << /Font << /F1 %d 0 R >> >>", fontN),
		[]byte("BT /F1 12 Tf 10 700 Td (Nested) Tj ET"),
	)

	// L1 Form XObject: invokes L2 from its stream body
	l1N := b.addStream(
		fmt.Sprintf("/Type /XObject /Subtype /Form /BBox [0 0 612 792] /Resources << /XObject << /L2 %d 0 R >> /Font << /F1 %d 0 R >> >>",
			l2N, fontN),
		[]byte("/L2 Do"),
	)

	// Page content: invoke L1
	pageContentN := b.addStream("", []byte("/L1 Do"))

	// Page
	pageN := b.addRaw(fmt.Sprintf(
		"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /XObject << /L1 %d 0 R >> >> /Contents %d 0 R >>",
		l1N, pageContentN,
	))

	pagesN := b.addRaw(fmt.Sprintf("<< /Type /Pages /Kids [%d 0 R] /Count 1 >>", pageN))
	catalogN := b.addRaw(fmt.Sprintf("<< /Type /Catalog /Pages %d 0 R >>", pagesN))

	return b.finalize(catalogN)
}

// buildTransformedGlyphXObjectPDF mimics Quartz-generated financial reports:
// the page scales a Form XObject, the Form supplies its own matrix, and each
// glyph is positioned by a nested cm operator while the text matrix stays at
// the origin. Accurate coordinates therefore require all three transforms.
func buildTransformedGlyphXObjectPDF(t *testing.T) []byte {
	t.Helper()

	b := newXObjPDFBuilder(20)
	fontN := b.addRaw("<< /Type /Font /Subtype /TrueType /BaseFont /Test /FirstChar 65 /LastChar 68 /Widths [600 600 600 600] >>")

	xobjContent := []byte(strings.Join([]string{
		"q 10 0 0 10 100 200 cm BT /F1 1 Tf 1 0 0 1 0 0 Tm (A) Tj ET Q",
		"q 10 0 0 10 106 200 cm BT /F1 1 Tf 1 0 0 1 0 0 Tm (B) Tj ET Q",
		"q 10 0 0 10 115 200 cm BT /F1 1 Tf 1 0 0 1 0 0 Tm (C) Tj ET Q",
	}, "\n"))
	xobjN := b.addStream(
		fmt.Sprintf("/Type /XObject /Subtype /Form /BBox [0 0 612 792] /Matrix [1 0 0 1 20 30] /Resources << /Font << /F1 %d 0 R >> >>", fontN),
		xobjContent,
	)

	// The direct page text after Q proves that the Form and graphics state are
	// restored rather than leaking their scale/translation into the caller.
	pageContent := []byte("q 0.5 0 0 0.5 0 0 cm /Fm1 Do Q BT /F1 10 Tf 1 0 0 1 10 20 Tm (D) Tj ET")
	pageContentN := b.addStream("", pageContent)
	pageN := b.addRaw(fmt.Sprintf(
		"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 %d 0 R >> /XObject << /Fm1 %d 0 R >> >> /Contents %d 0 R >>",
		fontN, xobjN, pageContentN,
	))
	pagesN := b.addRaw(fmt.Sprintf("<< /Type /Pages /Kids [%d 0 R] /Count 1 >>", pageN))
	catalogN := b.addRaw(fmt.Sprintf("<< /Type /Catalog /Pages %d 0 R >>", pagesN))
	return b.finalize(catalogN)
}

// buildImageXObjectPDF builds a PDF whose XObjects section contains only an
// Image XObject (Subtype /Image). The extractor must skip it silently.
//
//nolint:funlen // PDF construction is inherently verbose
func buildImageXObjectPDF(t *testing.T) []byte {
	t.Helper()

	b := newXObjPDFBuilder(15)

	// Minimal 1×1 pixel Image XObject.
	// /Subtype /Image — the extractor must skip this without error.
	imageN := b.addStream(
		"/Type /XObject /Subtype /Image /Width 1 /Height 1 /ColorSpace /DeviceGray /BitsPerComponent 8",
		[]byte{0xFF},
	)

	// Page content stream: just a Do referencing the image (no text operators)
	pageContentN := b.addStream("", []byte("/Im1 Do"))

	// Page
	pageN := b.addRaw(fmt.Sprintf(
		"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /XObject << /Im1 %d 0 R >> >> /Contents %d 0 R >>",
		imageN, pageContentN,
	))

	pagesN := b.addRaw(fmt.Sprintf("<< /Type /Pages /Kids [%d 0 R] /Count 1 >>", pageN))
	catalogN := b.addRaw(fmt.Sprintf("<< /Type /Catalog /Pages %d 0 R >>", pagesN))

	return b.finalize(catalogN)
}

// buildMissingXObjectPDF builds a PDF whose page content references a Form
// XObject that is not registered in the Resources dictionary.
//
//nolint:funlen // PDF construction is inherently verbose
func buildMissingXObjectPDF(t *testing.T) []byte {
	t.Helper()

	b := newXObjPDFBuilder(10)

	// Page content: /GHOST Do — "GHOST" is not in Resources
	pageContentN := b.addStream("", []byte("/GHOST Do"))

	// Page has no XObject resources at all
	pageN := b.addRaw(fmt.Sprintf(
		"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents %d 0 R >>",
		pageContentN,
	))

	pagesN := b.addRaw(fmt.Sprintf("<< /Type /Pages /Kids [%d 0 R] /Count 1 >>", pageN))
	catalogN := b.addRaw(fmt.Sprintf("<< /Type /Catalog /Pages %d 0 R >>", pagesN))

	return b.finalize(catalogN)
}

// buildDeepNestedXObjectPDF builds a PDF with XObject nesting exactly at
// maxXObjectDepth + 1 levels so the depth guard is triggered.
// At maxXObjectDepth levels the text "Top" is emitted; the innermost level
// that would exceed the cap must be silently skipped.
//
//nolint:funlen // PDF construction is inherently verbose
func buildDeepNestedXObjectPDF(t *testing.T) []byte {
	t.Helper()

	b := newXObjPDFBuilder(60) // plenty of room

	fontN := b.addRaw("<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>")

	// Build innermost XObject (one level past the guard) — its text should NOT appear.
	// This is a Form XObject where the stream body has the text operators.
	innermostN := b.addStream(
		fmt.Sprintf("/Type /XObject /Subtype /Form /BBox [0 0 612 792] /Resources << /Font << /F1 %d 0 R >> >>", fontN),
		[]byte("BT /F1 12 Tf 10 100 Td (TooDeep) Tj ET"),
	)

	// Wrap in maxXObjectDepth levels, each invoking the next via /INNER Do
	current := innermostN
	for i := 0; i < maxXObjectDepth; i++ {
		current = b.addStream(
			fmt.Sprintf("/Type /XObject /Subtype /Form /BBox [0 0 612 792] /Resources << /XObject << /INNER %d 0 R >> /Font << /F1 %d 0 R >> >>",
				current, fontN),
			[]byte("/INNER Do"),
		)
	}

	// Page invokes the outermost
	pageContentN := b.addStream("", []byte("/OUTER Do"))
	pageN := b.addRaw(fmt.Sprintf(
		"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /XObject << /OUTER %d 0 R >> >> /Contents %d 0 R >>",
		current, pageContentN,
	))

	pagesN := b.addRaw(fmt.Sprintf("<< /Type /Pages /Kids [%d 0 R] /Count 1 >>", pageN))
	catalogN := b.addRaw(fmt.Sprintf("<< /Type /Catalog /Pages %d 0 R >>", pagesN))

	return b.finalize(catalogN)
}

// ─── Helper to write a PDF to a temp file and open it ────────────────────────

func openPDFBytes(t *testing.T, pdfData []byte) *parser.Reader {
	t.Helper()
	dir := t.TempDir()
	path := filepath.Join(dir, "test.pdf")
	require.NoError(t, os.WriteFile(path, pdfData, 0600))
	rd, err := parser.OpenPDF(path)
	require.NoError(t, err)
	t.Cleanup(func() { _ = rd.Close() })
	return rd
}

// ─── Test 1: Simple font inside Form XObject ─────────────────────────────────

func TestFormXObject_SimpleFont_ExtractsText(t *testing.T) {
	pdfData := buildSimpleFontXObjectPDF(t)
	rd := openPDFBytes(t, pdfData)

	te := NewTextExtractor(rd)
	elements, err := te.ExtractFromPage(0)
	require.NoError(t, err)
	require.NotEmpty(t, elements, "expected text from Form XObject, got none")

	var sb strings.Builder
	for _, el := range elements {
		sb.WriteString(el.Text)
	}
	assert.Equal(t, "Hello World", sb.String(),
		"Form XObject with simple font must produce correct text")
}

func TestFormXObject_AppliesPageAndFormTransformsToGlyphGeometry(t *testing.T) {
	reader := openPDFBytes(t, buildTransformedGlyphXObjectPDF(t))
	extractor := NewTextExtractor(reader)

	elements, err := extractor.ExtractFromPage(0)
	require.NoError(t, err)
	require.Len(t, elements, 3)

	assert.Equal(t, "AB", elements[0].Text)
	assert.InDelta(t, 60, elements[0].X, 0.001)
	assert.InDelta(t, 115, elements[0].Y, 0.001)
	assert.InDelta(t, 6, elements[0].Width, 0.001)
	assert.InDelta(t, 5, elements[0].Height, 0.001)
	assert.InDelta(t, 5, elements[0].FontSize, 0.001)

	assert.Equal(t, "C", elements[1].Text)
	assert.InDelta(t, 67.5, elements[1].X, 0.001)
	assert.InDelta(t, 115, elements[1].Y, 0.001)
	assert.InDelta(t, 3, elements[1].Width, 0.001)

	assert.Equal(t, "D", elements[2].Text)
	assert.InDelta(t, 10, elements[2].X, 0.001)
	assert.InDelta(t, 20, elements[2].Y, 0.001)
	assert.InDelta(t, 6, elements[2].Width, 0.001)
	assert.InDelta(t, 10, elements[2].FontSize, 0.001)

	assert.Equal(t, "AB C\nD", AssembleText(elements))
}

// ─── Test 2: Type0 CID font inside Form XObject (TCPDF pattern) ──────────────

func TestFormXObject_Type0CIDFont_ExtractsText(t *testing.T) {
	pdfData := buildType0XObjectPDF(t)
	rd := openPDFBytes(t, pdfData)

	te := NewTextExtractor(rd)
	elements, err := te.ExtractFromPage(0)
	require.NoError(t, err)
	require.NotEmpty(t, elements, "Type0 CID font inside Form XObject must yield text elements")

	var sb strings.Builder
	for _, el := range elements {
		sb.WriteString(el.Text)
	}
	extracted := sb.String()
	assert.Equal(t, "CID", extracted,
		"Type0 CID font in Form XObject: expected 'CID', got %q", extracted)
}

// ─── Test 3: Nested Form XObjects ────────────────────────────────────────────

func TestFormXObject_Nested_ExtractsText(t *testing.T) {
	pdfData := buildNestedXObjectPDF(t)
	rd := openPDFBytes(t, pdfData)

	te := NewTextExtractor(rd)
	elements, err := te.ExtractFromPage(0)
	require.NoError(t, err)
	require.NotEmpty(t, elements, "nested XObject must yield text elements")

	var sb strings.Builder
	for _, el := range elements {
		sb.WriteString(el.Text)
	}
	assert.Equal(t, "Nested", sb.String(),
		"text from doubly-nested Form XObject must be extracted")
}

// ─── Test 4: Image XObject — must be silently skipped ────────────────────────

func TestFormXObject_ImageXObject_SkippedSilently(t *testing.T) {
	pdfData := buildImageXObjectPDF(t)
	rd := openPDFBytes(t, pdfData)

	te := NewTextExtractor(rd)
	elements, err := te.ExtractFromPage(0)
	require.NoError(t, err, "image Do must not cause an error")
	// No text elements expected (no text in the content stream)
	for _, el := range elements {
		assert.Empty(t, strings.TrimSpace(el.Text),
			"image XObject must not produce text elements, got %q", el.Text)
	}
}

// ─── Test 5: Missing XObject reference — must not panic ──────────────────────

func TestFormXObject_MissingReference_NoPanic(t *testing.T) {
	pdfData := buildMissingXObjectPDF(t)
	rd := openPDFBytes(t, pdfData)

	te := NewTextExtractor(rd)
	// Must not panic, must not return an error
	elements, err := te.ExtractFromPage(0)
	require.NoError(t, err, "missing XObject reference must not error")
	// No text produced
	assert.Empty(t, elements, "missing XObject must yield no text elements")
}

// ─── Test 6: Recursion depth guard ───────────────────────────────────────────

func TestFormXObject_DepthGuard_DoesNotPanic(t *testing.T) {
	pdfData := buildDeepNestedXObjectPDF(t)
	rd := openPDFBytes(t, pdfData)

	te := NewTextExtractor(rd)
	// Must not panic or loop infinitely regardless of nesting depth
	elements, err := te.ExtractFromPage(0)
	require.NoError(t, err, "depth guard must not surface an error")
	// The "TooDeep" string should NOT appear (it is one level past the cap)
	var allText strings.Builder
	for _, el := range elements {
		allText.WriteString(el.Text)
	}
	assert.NotContains(t, allText.String(), "TooDeep",
		"text beyond maxXObjectDepth must be suppressed")
}

// ─── Test 7: processFormXObject — internal unit tests ────────────────────────

func TestProcessFormXObject_NoResourcesNoXObject_NoPanic(t *testing.T) {
	// Create a bare extractor with no page resources
	te := &TextExtractor{
		textState:    NewTextState(),
		fontDecoders: make(map[string]*FontDecoder),
		// pageResources is nil — resolveXObject must handle this
	}
	// Must not panic
	te.processFormXObject("GHOST")
}

func TestProcessFormXObject_MaxDepthGuard_ReturnsImmediately(t *testing.T) {
	te := &TextExtractor{
		textState:    NewTextState(),
		fontDecoders: make(map[string]*FontDecoder),
		xobjectDepth: maxXObjectDepth, // already at limit
	}
	prevLen := len(te.elements)
	te.processFormXObject("ANY")
	assert.Equal(t, prevLen, len(te.elements), "at maxXObjectDepth, Do must be a no-op")
}

// ─── Test 8: resourceStack push/pop invariant ────────────────────────────────

func TestFormXObject_ResourceStack_RestoredAfterCall(t *testing.T) {
	// The test verifies that pageResources is correctly restored after a Do call
	// so a second call to the extractor sees the right fonts.
	pdfData := buildSimpleFontXObjectPDF(t)
	rd := openPDFBytes(t, pdfData)

	te := NewTextExtractor(rd)
	_, err := te.ExtractFromPage(0)
	require.NoError(t, err)

	// After extraction, resourceStack must be empty and depth must be 0.
	assert.Equal(t, 0, te.xobjectDepth, "xobjectDepth must be 0 after ExtractFromPage returns")
	assert.Empty(t, te.resourceStack, "resourceStack must be empty after ExtractFromPage returns")
}

// ─── Test 9: integration — real Correo Argentino PDF ─────────────────────────

// TestFormXObject_Integration_CorreoArgentinoLabel verifies that the real-world
// TCPDF shipping-label PDF (5 pages) yields meaningful text on every page.
//
// This PDF places all content in Form XObjects. Before the fix, all 4 CID-font
// pages returned empty strings. After the fix, each page contains shipping data.
func TestFormXObject_Integration_CorreoArgentinoLabel(t *testing.T) {
	const pdfPath = "../../testdata/pdfs/cid-fonts/correo_argentino_label.pdf"

	if _, err := os.Stat(pdfPath); os.IsNotExist(err) {
		t.Skipf("test PDF not found at %s — skipping integration test", pdfPath)
	}

	rd, err := parser.OpenPDF(pdfPath)
	require.NoError(t, err)
	defer func() { _ = rd.Close() }()

	count, err := rd.GetPageCount()
	require.NoError(t, err)
	assert.Equal(t, 5, count, "Correo Argentino label has 5 pages")

	// Expected substrings that must appear on every page
	// (from the actual content of the shipping label):
	mustContainAll := []string{
		"CLASICO",  // service type
		"F.PAGADO", // paid indicator
		"TCPDF",    // producer attribution
	}

	// Expected substrings that appear on specific pages only
	pageSpecific := map[int][]string{
		0: {"Ferrero Leandro", "HC359409442AR"},
		1: {"Fernando Dabbah", "HC359409439AR"},
		2: {"Noemi Beraldo", "HC359409408AR"},
		3: {"Maria Ester Ovcharyk", "HC359409399AR"},
		4: {"Nicolas Acosta", "HC359409385AR"},
	}

	for pageIdx := 0; pageIdx < count; pageIdx++ {
		te := NewTextExtractor(rd)
		elements, err := te.ExtractFromPage(pageIdx)
		require.NoError(t, err, "page %d must not error", pageIdx+1)
		require.NotEmpty(t, elements, "page %d must yield text elements (was empty before fix)", pageIdx+1)

		var sb strings.Builder
		for _, el := range elements {
			sb.WriteString(el.Text)
			sb.WriteString(" ")
		}
		pageText := sb.String()

		for _, want := range mustContainAll {
			assert.Contains(t, pageText, want,
				"page %d must contain %q", pageIdx+1, want)
		}

		if specific, ok := pageSpecific[pageIdx]; ok {
			for _, want := range specific {
				assert.Contains(t, pageText, want,
					"page %d must contain page-specific text %q", pageIdx+1, want)
			}
		}
	}
}

// TestFormXObject_Integration_CorreoArgentinoLabel_NoEmptyPages verifies the
// original bug report: before the fix, 4 of 5 pages returned empty strings.
// After the fix, no page must be empty.
func TestFormXObject_Integration_CorreoArgentinoLabel_NoEmptyPages(t *testing.T) {
	const pdfPath = "../../testdata/pdfs/cid-fonts/correo_argentino_label.pdf"

	if _, err := os.Stat(pdfPath); os.IsNotExist(err) {
		t.Skipf("test PDF not found at %s — skipping integration test", pdfPath)
	}

	rd, err := parser.OpenPDF(pdfPath)
	require.NoError(t, err)
	defer func() { _ = rd.Close() }()

	count, _ := rd.GetPageCount()

	for pageIdx := 0; pageIdx < count; pageIdx++ {
		te := NewTextExtractor(rd)
		elements, err := te.ExtractFromPage(pageIdx)
		require.NoError(t, err, "page %d", pageIdx+1)

		var sb strings.Builder
		for _, el := range elements {
			sb.WriteString(strings.TrimSpace(el.Text))
		}
		extracted := strings.TrimSpace(sb.String())

		assert.NotEmpty(t, extracted,
			"page %d returned empty text — Form XObject Do operator not processed", pageIdx+1)
	}
}

// TestExtractTextFromPage_CorreoArgentino verifies the public Document API
// works correctly end-to-end with the Correo Argentino PDF.
// This is the exact API that the issue reporter would use.
func TestExtractTextFromPage_CorreoArgentino(t *testing.T) {
	const pdfPath = "../../testdata/pdfs/cid-fonts/correo_argentino_label.pdf"
	if _, err := os.Stat(pdfPath); os.IsNotExist(err) {
		t.Skipf("test PDF not found at %s", pdfPath)
	}

	rd, err := parser.OpenPDF(pdfPath)
	require.NoError(t, err)
	defer func() { _ = rd.Close() }()

	for pageIdx := 0; pageIdx < 5; pageIdx++ {
		te := NewTextExtractor(rd)
		elements, err := te.ExtractFromPage(pageIdx)
		require.NoError(t, err, "page %d", pageIdx+1)

		var result string
		for _, elem := range elements {
			result += elem.Text + " "
		}

		assert.NotEmpty(t, strings.TrimSpace(result),
			"ExtractFromPage(%d) returned empty — regression", pageIdx)
	}
}
